//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParulBeautyCareDbClasses.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class parulbeautycareEntities : DbContext
    {
        public parulbeautycareEntities()
            : base("name=parulbeautycareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> PBLoginCheck(string staffMembercode, string staffMemberPassword)
        {
            var staffMembercodeParameter = staffMembercode != null ?
                new ObjectParameter("StaffMembercode", staffMembercode) :
                new ObjectParameter("StaffMembercode", typeof(string));
    
            var staffMemberPasswordParameter = staffMemberPassword != null ?
                new ObjectParameter("StaffMemberPassword", staffMemberPassword) :
                new ObjectParameter("StaffMemberPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBLoginCheck", staffMembercodeParameter, staffMemberPasswordParameter);
        }
    
        public virtual ObjectResult<PBLoginRtr_Result> PBLoginRtr(string staffMembercode, string staffMemberPassword)
        {
            var staffMembercodeParameter = staffMembercode != null ?
                new ObjectParameter("StaffMembercode", staffMembercode) :
                new ObjectParameter("StaffMembercode", typeof(string));
    
            var staffMemberPasswordParameter = staffMemberPassword != null ?
                new ObjectParameter("StaffMemberPassword", staffMemberPassword) :
                new ObjectParameter("StaffMemberPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBLoginRtr_Result>("PBLoginRtr", staffMembercodeParameter, staffMemberPasswordParameter);
        }
    
        public virtual ObjectResult<string> PBIntePageModuleInsUpd(string inteId, string moduleId, string pageId, string createDate, string createUser, string activeStatus, string moduleName, string pageName, string action)
        {
            var inteIdParameter = inteId != null ?
                new ObjectParameter("InteId", inteId) :
                new ObjectParameter("InteId", typeof(string));
    
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(string));
    
            var pageIdParameter = pageId != null ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("ActiveStatus", activeStatus) :
                new ObjectParameter("ActiveStatus", typeof(string));
    
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBIntePageModuleInsUpd", inteIdParameter, moduleIdParameter, pageIdParameter, createDateParameter, createUserParameter, activeStatusParameter, moduleNameParameter, pageNameParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBIntePageModuleRtr_Result> PBIntePageModuleRtr(string action, string moduleid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var moduleidParameter = moduleid != null ?
                new ObjectParameter("moduleid", moduleid) :
                new ObjectParameter("moduleid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBIntePageModuleRtr_Result>("PBIntePageModuleRtr", actionParameter, moduleidParameter);
        }
    
        public virtual ObjectResult<string> PBInteRoleModuleInsUpd(string id, string roleid, string modid, string isActive, string createdate, string createuser, string action, string mPInteId, string viewright, string insertright, string updateright, string deleteright, string updatedate, string updateuser)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var roleidParameter = roleid != null ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(string));
    
            var modidParameter = modid != null ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(string));
    
            var isActiveParameter = isActive != null ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var mPInteIdParameter = mPInteId != null ?
                new ObjectParameter("MPInteId", mPInteId) :
                new ObjectParameter("MPInteId", typeof(string));
    
            var viewrightParameter = viewright != null ?
                new ObjectParameter("viewright", viewright) :
                new ObjectParameter("viewright", typeof(string));
    
            var insertrightParameter = insertright != null ?
                new ObjectParameter("insertright", insertright) :
                new ObjectParameter("insertright", typeof(string));
    
            var updaterightParameter = updateright != null ?
                new ObjectParameter("updateright", updateright) :
                new ObjectParameter("updateright", typeof(string));
    
            var deleterightParameter = deleteright != null ?
                new ObjectParameter("deleteright", deleteright) :
                new ObjectParameter("deleteright", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var updateuserParameter = updateuser != null ?
                new ObjectParameter("updateuser", updateuser) :
                new ObjectParameter("updateuser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBInteRoleModuleInsUpd", idParameter, roleidParameter, modidParameter, isActiveParameter, createdateParameter, createuserParameter, actionParameter, mPInteIdParameter, viewrightParameter, insertrightParameter, updaterightParameter, deleterightParameter, updatedateParameter, updateuserParameter);
        }
    
        public virtual ObjectResult<PBInteRoleModuleRtr_Result> PBInteRoleModuleRtr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBInteRoleModuleRtr_Result>("PBInteRoleModuleRtr");
        }
    
        public virtual ObjectResult<string> PBModuleMasterInsUpd(string moduleId, string moduleName, string selfPage, string modulePriority, string faIcon, string isactive, string createDate, string updatedate, string createUser, string updateUser, string action)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(string));
    
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var selfPageParameter = selfPage != null ?
                new ObjectParameter("SelfPage", selfPage) :
                new ObjectParameter("SelfPage", typeof(string));
    
            var modulePriorityParameter = modulePriority != null ?
                new ObjectParameter("ModulePriority", modulePriority) :
                new ObjectParameter("ModulePriority", typeof(string));
    
            var faIconParameter = faIcon != null ?
                new ObjectParameter("FaIcon", faIcon) :
                new ObjectParameter("FaIcon", typeof(string));
    
            var isactiveParameter = isactive != null ?
                new ObjectParameter("Isactive", isactive) :
                new ObjectParameter("Isactive", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBModuleMasterInsUpd", moduleIdParameter, moduleNameParameter, selfPageParameter, modulePriorityParameter, faIconParameter, isactiveParameter, createDateParameter, updatedateParameter, createUserParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBModuleMasterRtr_Result> PBModuleMasterRtr(string action, string moduleid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var moduleidParameter = moduleid != null ?
                new ObjectParameter("moduleid", moduleid) :
                new ObjectParameter("moduleid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBModuleMasterRtr_Result>("PBModuleMasterRtr", actionParameter, moduleidParameter);
        }
    
        public virtual ObjectResult<string> PBPageMasterInsUpd(string pageId, string pageName, string pageUrl, string createDate, string createUser, string isActive, string pagePriority, string updatedate, string updateUser, string action)
        {
            var pageIdParameter = pageId != null ?
                new ObjectParameter("pageId", pageId) :
                new ObjectParameter("pageId", typeof(string));
    
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var pageUrlParameter = pageUrl != null ?
                new ObjectParameter("PageUrl", pageUrl) :
                new ObjectParameter("PageUrl", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var isActiveParameter = isActive != null ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(string));
    
            var pagePriorityParameter = pagePriority != null ?
                new ObjectParameter("PagePriority", pagePriority) :
                new ObjectParameter("PagePriority", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBPageMasterInsUpd", pageIdParameter, pageNameParameter, pageUrlParameter, createDateParameter, createUserParameter, isActiveParameter, pagePriorityParameter, updatedateParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBPageMasterRtr_Result> PBPageMasterRtr(string action, string pageid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var pageidParameter = pageid != null ?
                new ObjectParameter("pageid", pageid) :
                new ObjectParameter("pageid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBPageMasterRtr_Result>("PBPageMasterRtr", actionParameter, pageidParameter);
        }
    
        public virtual ObjectResult<string> PBRoleMasterInsUpd(string roleId, string rolename, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            var rolenameParameter = rolename != null ?
                new ObjectParameter("Rolename", rolename) :
                new ObjectParameter("Rolename", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBRoleMasterInsUpd", roleIdParameter, rolenameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBRoleMasterRetrieve_Result> PBRoleMasterRetrieve(string action, string companycode)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBRoleMasterRetrieve_Result>("PBRoleMasterRetrieve", actionParameter, companycodeParameter);
        }
    
        public virtual ObjectResult<string> PBStaffMasterInsUpd(string staffId, string staffCode, string staffName, string contact, string gender, string password, string roleId, string isactive, string companyCode, string createDate, string updatedate, string createUser, string updateUser, string action)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            var staffCodeParameter = staffCode != null ?
                new ObjectParameter("StaffCode", staffCode) :
                new ObjectParameter("StaffCode", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            var isactiveParameter = isactive != null ?
                new ObjectParameter("Isactive", isactive) :
                new ObjectParameter("Isactive", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBStaffMasterInsUpd", staffIdParameter, staffCodeParameter, staffNameParameter, contactParameter, genderParameter, passwordParameter, roleIdParameter, isactiveParameter, companyCodeParameter, createDateParameter, updatedateParameter, createUserParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBStaffMasterRtr_Result> PBStaffMasterRtr(string companyCode, string action)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBStaffMasterRtr_Result>("PBStaffMasterRtr", companyCodeParameter, actionParameter);
        }
    }
}
