//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParulBeautyCareDbClasses.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class parulbeautycareEntities : DbContext
    {
        public parulbeautycareEntities()
            : base("name=parulbeautycareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> PBCategoryMasterInsUpd(string categoryId, string categoryname, string description, string companyCode, string activeStatus, string createdate, string updatedate, string createuser, string action)
        {
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(string));
    
            var categorynameParameter = categoryname != null ?
                new ObjectParameter("Categoryname", categoryname) :
                new ObjectParameter("Categoryname", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("activeStatus", activeStatus) :
                new ObjectParameter("activeStatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBCategoryMasterInsUpd", categoryIdParameter, categorynameParameter, descriptionParameter, companyCodeParameter, activeStatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBCategoryMasterRetrieve_Result> PBCategoryMasterRetrieve(string action, string companycode, string id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBCategoryMasterRetrieve_Result>("PBCategoryMasterRetrieve", actionParameter, companycodeParameter, idParameter);
        }
    
        public virtual ObjectResult<string> PBIntePageModuleInsUpd(string inteId, string moduleId, string pageId, string createDate, string createUser, string activeStatus, string moduleName, string pageName, string action)
        {
            var inteIdParameter = inteId != null ?
                new ObjectParameter("InteId", inteId) :
                new ObjectParameter("InteId", typeof(string));
    
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(string));
    
            var pageIdParameter = pageId != null ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("ActiveStatus", activeStatus) :
                new ObjectParameter("ActiveStatus", typeof(string));
    
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBIntePageModuleInsUpd", inteIdParameter, moduleIdParameter, pageIdParameter, createDateParameter, createUserParameter, activeStatusParameter, moduleNameParameter, pageNameParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBIntePageModuleRtr_Result> PBIntePageModuleRtr(string action, string moduleid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var moduleidParameter = moduleid != null ?
                new ObjectParameter("moduleid", moduleid) :
                new ObjectParameter("moduleid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBIntePageModuleRtr_Result>("PBIntePageModuleRtr", actionParameter, moduleidParameter);
        }
    
        public virtual ObjectResult<string> PBInteRoleModuleInsUpd(string id, string roleid, string modid, string isActive, string createdate, string createuser, string action, string mPInteId, string viewright, string insertright, string updateright, string deleteright, string updatedate, string updateuser)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var roleidParameter = roleid != null ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(string));
    
            var modidParameter = modid != null ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(string));
    
            var isActiveParameter = isActive != null ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var mPInteIdParameter = mPInteId != null ?
                new ObjectParameter("MPInteId", mPInteId) :
                new ObjectParameter("MPInteId", typeof(string));
    
            var viewrightParameter = viewright != null ?
                new ObjectParameter("viewright", viewright) :
                new ObjectParameter("viewright", typeof(string));
    
            var insertrightParameter = insertright != null ?
                new ObjectParameter("insertright", insertright) :
                new ObjectParameter("insertright", typeof(string));
    
            var updaterightParameter = updateright != null ?
                new ObjectParameter("updateright", updateright) :
                new ObjectParameter("updateright", typeof(string));
    
            var deleterightParameter = deleteright != null ?
                new ObjectParameter("deleteright", deleteright) :
                new ObjectParameter("deleteright", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var updateuserParameter = updateuser != null ?
                new ObjectParameter("updateuser", updateuser) :
                new ObjectParameter("updateuser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBInteRoleModuleInsUpd", idParameter, roleidParameter, modidParameter, isActiveParameter, createdateParameter, createuserParameter, actionParameter, mPInteIdParameter, viewrightParameter, insertrightParameter, updaterightParameter, deleterightParameter, updatedateParameter, updateuserParameter);
        }
    
        public virtual ObjectResult<PBInteRoleModuleRtr_Result> PBInteRoleModuleRtr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBInteRoleModuleRtr_Result>("PBInteRoleModuleRtr");
        }
    
        public virtual ObjectResult<string> PBLoginCheck(string staffMembercode, string staffMemberPassword)
        {
            var staffMembercodeParameter = staffMembercode != null ?
                new ObjectParameter("StaffMembercode", staffMembercode) :
                new ObjectParameter("StaffMembercode", typeof(string));
    
            var staffMemberPasswordParameter = staffMemberPassword != null ?
                new ObjectParameter("StaffMemberPassword", staffMemberPassword) :
                new ObjectParameter("StaffMemberPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBLoginCheck", staffMembercodeParameter, staffMemberPasswordParameter);
        }
    
        public virtual ObjectResult<PBLoginRtr_Result> PBLoginRtr(string staffMembercode, string staffMemberPassword)
        {
            var staffMembercodeParameter = staffMembercode != null ?
                new ObjectParameter("StaffMembercode", staffMembercode) :
                new ObjectParameter("StaffMembercode", typeof(string));
    
            var staffMemberPasswordParameter = staffMemberPassword != null ?
                new ObjectParameter("StaffMemberPassword", staffMemberPassword) :
                new ObjectParameter("StaffMemberPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBLoginRtr_Result>("PBLoginRtr", staffMembercodeParameter, staffMemberPasswordParameter);
        }
    
        public virtual ObjectResult<PBMenuRightsRtr_Result> PBMenuRightsRtr(string usercode, string pagename)
        {
            var usercodeParameter = usercode != null ?
                new ObjectParameter("Usercode", usercode) :
                new ObjectParameter("Usercode", typeof(string));
    
            var pagenameParameter = pagename != null ?
                new ObjectParameter("pagename", pagename) :
                new ObjectParameter("pagename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBMenuRightsRtr_Result>("PBMenuRightsRtr", usercodeParameter, pagenameParameter);
        }
    
        public virtual ObjectResult<PBMenuRtr_Result> PBMenuRtr(string roleid)
        {
            var roleidParameter = roleid != null ?
                new ObjectParameter("Roleid", roleid) :
                new ObjectParameter("Roleid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBMenuRtr_Result>("PBMenuRtr", roleidParameter);
        }
    
        public virtual ObjectResult<string> PBModuleMasterInsUpd(string moduleId, string moduleName, string selfPage, string modulePriority, string faIcon, string isactive, string createDate, string updatedate, string createUser, string updateUser, string action)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(string));
    
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var selfPageParameter = selfPage != null ?
                new ObjectParameter("SelfPage", selfPage) :
                new ObjectParameter("SelfPage", typeof(string));
    
            var modulePriorityParameter = modulePriority != null ?
                new ObjectParameter("ModulePriority", modulePriority) :
                new ObjectParameter("ModulePriority", typeof(string));
    
            var faIconParameter = faIcon != null ?
                new ObjectParameter("FaIcon", faIcon) :
                new ObjectParameter("FaIcon", typeof(string));
    
            var isactiveParameter = isactive != null ?
                new ObjectParameter("Isactive", isactive) :
                new ObjectParameter("Isactive", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBModuleMasterInsUpd", moduleIdParameter, moduleNameParameter, selfPageParameter, modulePriorityParameter, faIconParameter, isactiveParameter, createDateParameter, updatedateParameter, createUserParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBModuleMasterRtr_Result> PBModuleMasterRtr(string action, string moduleid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var moduleidParameter = moduleid != null ?
                new ObjectParameter("moduleid", moduleid) :
                new ObjectParameter("moduleid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBModuleMasterRtr_Result>("PBModuleMasterRtr", actionParameter, moduleidParameter);
        }
    
        public virtual ObjectResult<string> PBPageMasterInsUpd(string pageId, string pageName, string pageUrl, string createDate, string createUser, string isActive, string pagePriority, string updatedate, string updateUser, string action)
        {
            var pageIdParameter = pageId != null ?
                new ObjectParameter("pageId", pageId) :
                new ObjectParameter("pageId", typeof(string));
    
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var pageUrlParameter = pageUrl != null ?
                new ObjectParameter("PageUrl", pageUrl) :
                new ObjectParameter("PageUrl", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var isActiveParameter = isActive != null ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(string));
    
            var pagePriorityParameter = pagePriority != null ?
                new ObjectParameter("PagePriority", pagePriority) :
                new ObjectParameter("PagePriority", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBPageMasterInsUpd", pageIdParameter, pageNameParameter, pageUrlParameter, createDateParameter, createUserParameter, isActiveParameter, pagePriorityParameter, updatedateParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBPageMasterRtr_Result> PBPageMasterRtr(string action, string pageid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var pageidParameter = pageid != null ?
                new ObjectParameter("pageid", pageid) :
                new ObjectParameter("pageid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBPageMasterRtr_Result>("PBPageMasterRtr", actionParameter, pageidParameter);
        }
    
        public virtual ObjectResult<string> PBProductMasterInsUpd(string productId, string productCode, string productName, string numberOfPerson, string productTypeId, string isactive, string companyCode, string createDate, string updatedate, string createUser, string updateUser, string action)
        {
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var numberOfPersonParameter = numberOfPerson != null ?
                new ObjectParameter("NumberOfPerson", numberOfPerson) :
                new ObjectParameter("NumberOfPerson", typeof(string));
    
            var productTypeIdParameter = productTypeId != null ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(string));
    
            var isactiveParameter = isactive != null ?
                new ObjectParameter("Isactive", isactive) :
                new ObjectParameter("Isactive", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBProductMasterInsUpd", productIdParameter, productCodeParameter, productNameParameter, numberOfPersonParameter, productTypeIdParameter, isactiveParameter, companyCodeParameter, createDateParameter, updatedateParameter, createUserParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBProductMasterRtr_Result> PBProductMasterRtr(string companyCode, string action, string productId)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBProductMasterRtr_Result>("PBProductMasterRtr", companyCodeParameter, actionParameter, productIdParameter);
        }
    
        public virtual ObjectResult<string> PBProductTypeMasterInsUpd(string productTypeId, string productName, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var productTypeIdParameter = productTypeId != null ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBProductTypeMasterInsUpd", productTypeIdParameter, productNameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBProductTypeMasterRetrieve_Result> PBProductTypeMasterRetrieve(string action, string companycode, string productTypeId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var productTypeIdParameter = productTypeId != null ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBProductTypeMasterRetrieve_Result>("PBProductTypeMasterRetrieve", actionParameter, companycodeParameter, productTypeIdParameter);
        }
    
        public virtual ObjectResult<string> PBRoleMasterInsUpd(string roleId, string rolename, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            var rolenameParameter = rolename != null ?
                new ObjectParameter("Rolename", rolename) :
                new ObjectParameter("Rolename", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBRoleMasterInsUpd", roleIdParameter, rolenameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBRoleMasterRetrieve_Result> PBRoleMasterRetrieve(string action, string companycode, string id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBRoleMasterRetrieve_Result>("PBRoleMasterRetrieve", actionParameter, companycodeParameter, idParameter);
        }
    
        public virtual ObjectResult<string> PBStaffMasterInsUpd(string staffId, string staffCode, string staffName, string contact, string gender, string password, string roleId, string isactive, string companyCode, string createDate, string updatedate, string createUser, string updateUser, string action)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            var staffCodeParameter = staffCode != null ?
                new ObjectParameter("StaffCode", staffCode) :
                new ObjectParameter("StaffCode", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            var isactiveParameter = isactive != null ?
                new ObjectParameter("Isactive", isactive) :
                new ObjectParameter("Isactive", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("Updatedate", updatedate) :
                new ObjectParameter("Updatedate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBStaffMasterInsUpd", staffIdParameter, staffCodeParameter, staffNameParameter, contactParameter, genderParameter, passwordParameter, roleIdParameter, isactiveParameter, companyCodeParameter, createDateParameter, updatedateParameter, createUserParameter, updateUserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBStaffMasterRtr_Result> PBStaffMasterRtr(string companyCode, string action, string staffId)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBStaffMasterRtr_Result>("PBStaffMasterRtr", companyCodeParameter, actionParameter, staffIdParameter);
        }
    
        public virtual ObjectResult<string> PBStatusMasterInsUpd(string statusId, string statusname, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var statusIdParameter = statusId != null ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(string));
    
            var statusnameParameter = statusname != null ?
                new ObjectParameter("Statusname", statusname) :
                new ObjectParameter("Statusname", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBStatusMasterInsUpd", statusIdParameter, statusnameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBStatusMasterRetrieve_Result> PBStatusMasterRetrieve(string action, string companycode, string statusId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var statusIdParameter = statusId != null ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBStatusMasterRetrieve_Result>("PBStatusMasterRetrieve", actionParameter, companycodeParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<string> PBSubCategoryMasterInsUpd(string subCategoryId, string subCategoryname, string categoryId, string isMultiPerson, string numberOfPerson, string yearId, string noOfSitting, string timeDuraion, string amount, string companyCode, string activeStatus, string createdate, string updatedate, string createuser, string action)
        {
            var subCategoryIdParameter = subCategoryId != null ?
                new ObjectParameter("SubCategoryId", subCategoryId) :
                new ObjectParameter("SubCategoryId", typeof(string));
    
            var subCategorynameParameter = subCategoryname != null ?
                new ObjectParameter("SubCategoryname", subCategoryname) :
                new ObjectParameter("SubCategoryname", typeof(string));
    
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(string));
    
            var isMultiPersonParameter = isMultiPerson != null ?
                new ObjectParameter("IsMultiPerson", isMultiPerson) :
                new ObjectParameter("IsMultiPerson", typeof(string));
    
            var numberOfPersonParameter = numberOfPerson != null ?
                new ObjectParameter("NumberOfPerson", numberOfPerson) :
                new ObjectParameter("NumberOfPerson", typeof(string));
    
            var yearIdParameter = yearId != null ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(string));
    
            var noOfSittingParameter = noOfSitting != null ?
                new ObjectParameter("NoOfSitting", noOfSitting) :
                new ObjectParameter("NoOfSitting", typeof(string));
    
            var timeDuraionParameter = timeDuraion != null ?
                new ObjectParameter("TimeDuraion", timeDuraion) :
                new ObjectParameter("TimeDuraion", typeof(string));
    
            var amountParameter = amount != null ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("activeStatus", activeStatus) :
                new ObjectParameter("activeStatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBSubCategoryMasterInsUpd", subCategoryIdParameter, subCategorynameParameter, categoryIdParameter, isMultiPersonParameter, numberOfPersonParameter, yearIdParameter, noOfSittingParameter, timeDuraionParameter, amountParameter, companyCodeParameter, activeStatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBSubCategoryMasterRetrieve_Result> PBSubCategoryMasterRetrieve(string action, string companycode, string subCategoryId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var subCategoryIdParameter = subCategoryId != null ?
                new ObjectParameter("SubCategoryId", subCategoryId) :
                new ObjectParameter("SubCategoryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBSubCategoryMasterRetrieve_Result>("PBSubCategoryMasterRetrieve", actionParameter, companycodeParameter, subCategoryIdParameter);
        }
    
        public virtual ObjectResult<string> PBTimeSlotMasterInsUpd(string slotId, string slotname, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var slotIdParameter = slotId != null ?
                new ObjectParameter("SlotId", slotId) :
                new ObjectParameter("SlotId", typeof(string));
    
            var slotnameParameter = slotname != null ?
                new ObjectParameter("Slotname", slotname) :
                new ObjectParameter("Slotname", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBTimeSlotMasterInsUpd", slotIdParameter, slotnameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBTimeSlotMasterRetrieve_Result> PBTimeSlotMasterRetrieve(string action, string companycode, string slotId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var slotIdParameter = slotId != null ?
                new ObjectParameter("SlotId", slotId) :
                new ObjectParameter("SlotId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBTimeSlotMasterRetrieve_Result>("PBTimeSlotMasterRetrieve", actionParameter, companycodeParameter, slotIdParameter);
        }
    
        public virtual ObjectResult<string> PBYearMasterInsUpd(string yearId, string yearperiod, string fromDate, string toDate, string companyCode, string isActive, string createdate, string updatedate, string createuser, string action)
        {
            var yearIdParameter = yearId != null ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(string));
    
            var yearperiodParameter = yearperiod != null ?
                new ObjectParameter("Yearperiod", yearperiod) :
                new ObjectParameter("Yearperiod", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var isActiveParameter = isActive != null ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBYearMasterInsUpd", yearIdParameter, yearperiodParameter, fromDateParameter, toDateParameter, companyCodeParameter, isActiveParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBYearMasterRetrieve_Result> PBYearMasterRetrieve(string action, string companycode, string yearId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var yearIdParameter = yearId != null ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBYearMasterRetrieve_Result>("PBYearMasterRetrieve", actionParameter, companycodeParameter, yearIdParameter);
        }
    
        public virtual ObjectResult<PBDepartmentMasterRetrieve_Result> PBDepartmentMasterRetrieve(string action, string companycode, string id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBDepartmentMasterRetrieve_Result>("PBDepartmentMasterRetrieve", actionParameter, companycodeParameter, idParameter);
        }
    
        public virtual ObjectResult<string> PBStockPurchaseMasterInsUpd(string purchaseId, string companyCode, string createDate, string createUser, string updateDate, string updateUser, string productId, string productTypeId, string quantity, string mfgDate, string expDate, string purchaseDate, string vendor, string deptId, string action)
        {
            var purchaseIdParameter = purchaseId != null ?
                new ObjectParameter("PurchaseId", purchaseId) :
                new ObjectParameter("PurchaseId", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateDateParameter = updateDate != null ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            var productTypeIdParameter = productTypeId != null ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(string));
    
            var quantityParameter = quantity != null ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(string));
    
            var mfgDateParameter = mfgDate != null ?
                new ObjectParameter("MfgDate", mfgDate) :
                new ObjectParameter("MfgDate", typeof(string));
    
            var expDateParameter = expDate != null ?
                new ObjectParameter("ExpDate", expDate) :
                new ObjectParameter("ExpDate", typeof(string));
    
            var purchaseDateParameter = purchaseDate != null ?
                new ObjectParameter("PurchaseDate", purchaseDate) :
                new ObjectParameter("PurchaseDate", typeof(string));
    
            var vendorParameter = vendor != null ?
                new ObjectParameter("Vendor", vendor) :
                new ObjectParameter("Vendor", typeof(string));
    
            var deptIdParameter = deptId != null ?
                new ObjectParameter("DeptId", deptId) :
                new ObjectParameter("DeptId", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBStockPurchaseMasterInsUpd", purchaseIdParameter, companyCodeParameter, createDateParameter, createUserParameter, updateDateParameter, updateUserParameter, productIdParameter, productTypeIdParameter, quantityParameter, mfgDateParameter, expDateParameter, purchaseDateParameter, vendorParameter, deptIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBStockPurchaseRetrieve_Result> PBStockPurchaseRetrieve(string action, string companycode, string purchaseid)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var companycodeParameter = companycode != null ?
                new ObjectParameter("companycode", companycode) :
                new ObjectParameter("companycode", typeof(string));
    
            var purchaseidParameter = purchaseid != null ?
                new ObjectParameter("purchaseid", purchaseid) :
                new ObjectParameter("purchaseid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBStockPurchaseRetrieve_Result>("PBStockPurchaseRetrieve", actionParameter, companycodeParameter, purchaseidParameter);
        }
    
        public virtual ObjectResult<string> PBDepartmentMasterInsUpd(string departmentId, string departmentname, string companyCode, string activestatus, string createdate, string updatedate, string createuser, string action)
        {
            var departmentIdParameter = departmentId != null ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(string));
    
            var departmentnameParameter = departmentname != null ?
                new ObjectParameter("Departmentname", departmentname) :
                new ObjectParameter("Departmentname", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var activestatusParameter = activestatus != null ?
                new ObjectParameter("activestatus", activestatus) :
                new ObjectParameter("activestatus", typeof(string));
    
            var createdateParameter = createdate != null ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(string));
    
            var updatedateParameter = updatedate != null ?
                new ObjectParameter("updatedate", updatedate) :
                new ObjectParameter("updatedate", typeof(string));
    
            var createuserParameter = createuser != null ?
                new ObjectParameter("createuser", createuser) :
                new ObjectParameter("createuser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBDepartmentMasterInsUpd", departmentIdParameter, departmentnameParameter, companyCodeParameter, activestatusParameter, createdateParameter, updatedateParameter, createuserParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBStockAllocationRetrieve_Result> PBStockAllocationRetrieve(string action, string stockAllocationId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var stockAllocationIdParameter = stockAllocationId != null ?
                new ObjectParameter("StockAllocationId", stockAllocationId) :
                new ObjectParameter("StockAllocationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBStockAllocationRetrieve_Result>("PBStockAllocationRetrieve", actionParameter, stockAllocationIdParameter);
        }
    
        public virtual ObjectResult<string> PBStockAllocationMasterInsUpd(string stockAllocationId, string productId, string qty, string allocationDate, string allocateUser, string staffId, string updateDate, string updateUser, string stockUsed, string createDate, string createUser, string noOfPerson, string personUsed, string action)
        {
            var stockAllocationIdParameter = stockAllocationId != null ?
                new ObjectParameter("StockAllocationId", stockAllocationId) :
                new ObjectParameter("StockAllocationId", typeof(string));
    
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(string));
    
            var allocationDateParameter = allocationDate != null ?
                new ObjectParameter("AllocationDate", allocationDate) :
                new ObjectParameter("AllocationDate", typeof(string));
    
            var allocateUserParameter = allocateUser != null ?
                new ObjectParameter("AllocateUser", allocateUser) :
                new ObjectParameter("AllocateUser", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            var updateDateParameter = updateDate != null ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var stockUsedParameter = stockUsed != null ?
                new ObjectParameter("StockUsed", stockUsed) :
                new ObjectParameter("StockUsed", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var noOfPersonParameter = noOfPerson != null ?
                new ObjectParameter("NoOfPerson", noOfPerson) :
                new ObjectParameter("NoOfPerson", typeof(string));
    
            var personUsedParameter = personUsed != null ?
                new ObjectParameter("PersonUsed", personUsed) :
                new ObjectParameter("PersonUsed", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PBStockAllocationMasterInsUpd", stockAllocationIdParameter, productIdParameter, qtyParameter, allocationDateParameter, allocateUserParameter, staffIdParameter, updateDateParameter, updateUserParameter, stockUsedParameter, createDateParameter, createUserParameter, noOfPersonParameter, personUsedParameter, actionParameter);
        }
    
        public virtual int PBBookingInsert(string bookingId, string customerId, string contactNo, string customerName, string address, string bookDate, string createDate, string createUser, string updateDate, string updateUser, string noOfPerson, string totalAmount, string discountPerc, string discount, string finalAmount, string advanceBookingCharge, string paidAmount, string companyCode, string functionDate, string readyTime, string status, string action)
        {
            var bookingIdParameter = bookingId != null ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(string));
    
            var customerIdParameter = customerId != null ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var bookDateParameter = bookDate != null ?
                new ObjectParameter("BookDate", bookDate) :
                new ObjectParameter("BookDate", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateDateParameter = updateDate != null ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var noOfPersonParameter = noOfPerson != null ?
                new ObjectParameter("NoOfPerson", noOfPerson) :
                new ObjectParameter("NoOfPerson", typeof(string));
    
            var totalAmountParameter = totalAmount != null ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(string));
    
            var discountPercParameter = discountPerc != null ?
                new ObjectParameter("DiscountPerc", discountPerc) :
                new ObjectParameter("DiscountPerc", typeof(string));
    
            var discountParameter = discount != null ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(string));
    
            var finalAmountParameter = finalAmount != null ?
                new ObjectParameter("FinalAmount", finalAmount) :
                new ObjectParameter("FinalAmount", typeof(string));
    
            var advanceBookingChargeParameter = advanceBookingCharge != null ?
                new ObjectParameter("AdvanceBookingCharge", advanceBookingCharge) :
                new ObjectParameter("AdvanceBookingCharge", typeof(string));
    
            var paidAmountParameter = paidAmount != null ?
                new ObjectParameter("PaidAmount", paidAmount) :
                new ObjectParameter("PaidAmount", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var functionDateParameter = functionDate != null ?
                new ObjectParameter("FunctionDate", functionDate) :
                new ObjectParameter("FunctionDate", typeof(string));
    
            var readyTimeParameter = readyTime != null ?
                new ObjectParameter("ReadyTime", readyTime) :
                new ObjectParameter("ReadyTime", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PBBookingInsert", bookingIdParameter, customerIdParameter, contactNoParameter, customerNameParameter, addressParameter, bookDateParameter, createDateParameter, createUserParameter, updateDateParameter, updateUserParameter, noOfPersonParameter, totalAmountParameter, discountPercParameter, discountParameter, finalAmountParameter, advanceBookingChargeParameter, paidAmountParameter, companyCodeParameter, functionDateParameter, readyTimeParameter, statusParameter, actionParameter);
        }
    
        public virtual ObjectResult<PBAvailableStockRtr_Result> PBAvailableStockRtr(string staffid)
        {
            var staffidParameter = staffid != null ?
                new ObjectParameter("staffid", staffid) :
                new ObjectParameter("staffid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PBAvailableStockRtr_Result>("PBAvailableStockRtr", staffidParameter);
        }
    
        public virtual int PBStockTransferInsert(string stockHeaderId, string transferDate, string fromStaffId, string toStaffId, string createDate, string createUser, string updateDate, string updateUser, string action)
        {
            var stockHeaderIdParameter = stockHeaderId != null ?
                new ObjectParameter("StockHeaderId", stockHeaderId) :
                new ObjectParameter("StockHeaderId", typeof(string));
    
            var transferDateParameter = transferDate != null ?
                new ObjectParameter("TransferDate", transferDate) :
                new ObjectParameter("TransferDate", typeof(string));
    
            var fromStaffIdParameter = fromStaffId != null ?
                new ObjectParameter("FromStaffId", fromStaffId) :
                new ObjectParameter("FromStaffId", typeof(string));
    
            var toStaffIdParameter = toStaffId != null ?
                new ObjectParameter("ToStaffId", toStaffId) :
                new ObjectParameter("ToStaffId", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var updateDateParameter = updateDate != null ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PBStockTransferInsert", stockHeaderIdParameter, transferDateParameter, fromStaffIdParameter, toStaffIdParameter, createDateParameter, createUserParameter, updateDateParameter, updateUserParameter, actionParameter);
        }
    }
}
